backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "accueil"
        fields:
          - { label: "Titre principal", name: "titre", widget: "string" }
          - { label: "Sous-titre", name: "soustitre", widget: "string" }
          - { label: "Texte", name: "texte", widget: "text" }
